import * as XLSX from "xlsx";

export type ReconciliationStatus = "MATCH"|"QTY_MISMATCH"|"VALUE_MISMATCH"|"QTY_AND_VALUE_MISMATCH"|"MISSING_INTERNAL"|"MISSING_PRINCIPAL"|"UNMAPPED_SKU"|"UNIT_CONVERSION_ERROR"|"INVALID_DATA";
export type AmountComponent = "gross"|"discount"|"dpp"|"tax"|"net";
export interface AmountDifference { component: AmountComponent; accurate: number; kino: number; difference: number; }
type TransactionClass = "NORMAL"|"BONUS"|"RETURN";
type MappingStatus = "OK"|"UNMAPPED_SKU"|"UNIT_CONVERSION_ERROR"|"INVALID_DATA";
type Row = unknown[];
export interface CanonicalSalesLine { source:"ACCURATE"|"PRINCIPAL"; sourceRowNumber:number; documentNumber:string; orderNumber:string; transactionDate:string; customerCodeRaw:string; customerCodeInternal:string; salesmanCodeRaw:string; salesmanCodeInternal:string; productCodeRaw:string; productCodeInternal:string; transactionClass:TransactionClass; quantitySmallest:number; unitSmallest:string; grossAmount:number; discountAmount:number; dppAmount:number; taxAmount:number; netAmount:number; mappingStatus:MappingStatus; }
export interface ReconciliationResult { orderNumber:string; internalProductCode:string; transactionClass:TransactionClass; accurateQuantity:number; principalQuantity:number; quantityDifference:number; accurateNet:number; principalNet:number; valueDifference:number; amountDifferences:AmountDifference[]; status:ReconciliationStatus; warnings:string[]; accurateSourceRows:number[]; principalSourceRows:number[]; }
export interface ReconciliationOutput { accurateLines:CanonicalSalesLine[]; kinoLines:CanonicalSalesLine[]; results:ReconciliationResult[]; summary:Record<ReconciliationStatus,number>; }
const SCALE=10_000, ALIASES:Record<string,string>={BT:"BTL",BTL:"BTL",TUB:"TUBE",TUBE:"TUBE",INB:"BOX",BOX:"BOX"};
const STATUSES:ReconciliationStatus[]=["MATCH","QTY_MISMATCH","VALUE_MISMATCH","QTY_AND_VALUE_MISMATCH","MISSING_INTERNAL","MISSING_PRINCIPAL","UNMAPPED_SKU","UNIT_CONVERSION_ERROR","INVALID_DATA"];
const tx=(v:unknown)=>String(v??"").replace(/\u00a0/g," ").replace(/[\u200B-\u200D\uFEFF]/g,"").trim().toUpperCase();
const u=(v:unknown)=>ALIASES[tx(v)]??tx(v);
function num(v:unknown,name:string,row:number) { if(v==null||tx(v)==="") return 0; const n=typeof v==="number"?v:Number(String(v).replace(/,/g,"")); if(!Number.isFinite(n)) throw Error(`${name} tidak valid pada baris ${row}`); return n; }
function mon(v:unknown,name:string,row:number) { const n=Math.round(num(v,name,row)*SCALE); if(!Number.isSafeInteger(n)) throw Error(`${name} terlalu besar pada baris ${row}`); return n; }
function date(v:unknown,name:string,row:number) { if(typeof v==="number"&&Number.isFinite(v)) return new Date(Date.UTC(1899,11,30)+Math.floor(v)*86400000).toISOString().slice(0,10); const s=tx(v); if(!/^\d{4}-\d{2}-\d{2}$/.test(s)) throw Error(`${name} tidak valid pada baris ${row}`); return s; }
function ord(v:unknown,name:string,row:number) { const s=tx(v), ids=[...(s.match(/1671-SOP-\d+/g)??[]),...([...s.matchAll(/(?:FK\/BFG|FK|BFG)-(\d+)/g)].map(m=>`BFG-${m[1]}`))]; if(ids.length!==1) throw Error(`${name} harus memuat tepat satu nomor order pada baris ${row}`); return ids[0]; }
function rows(buf:Buffer|Uint8Array,sheet:string) { if(!buf?.byteLength) throw Error("File XLSX kosong"); const w=XLSX.read(buf,{type:"buffer",raw:true,cellFormula:false}), sh=w.Sheets[sheet]; if(!sh?.["!ref"]) throw Error(`Sheet ${sheet} tidak ditemukan atau kosong`); return XLSX.utils.sheet_to_json(sh,{header:1,raw:true,defval:null,blankrows:false}) as Row[]; }
function head(rs:Row[],need:string[],limit=10) { for(let i=0;i<Math.min(rs.length,limit);i++){const c=new Map<string,number>();rs[i].forEach((x,j)=>{if(tx(x))c.set(tx(x),j)});if(need.every(n=>c.has(n)))return {i,c}} throw Error(`Header wajib tidak ditemukan: ${need.join(", ")}`); }
const val=(r:Row,c:Map<string,number>,n:string)=>c.has(n)?r[c.get(n)!]:null;
function req(r:Row,c:Map<string,number>,n:string,line:number) { const s=tx(val(r,c,n));if(!s)throw Error(`${n} kosong pada baris ${line}`);return s; }
const klass=(v:unknown):TransactionClass=>tx(v).includes("RETUR")||tx(v).includes("RETURN")?"RETURN":tx(v).includes("BONUS")?"BONUS":"NORMAL";

interface KinoMappings { products:Map<string,{internal:string;unit:string}>;customers:Map<string,string>;salesmen:Map<string,string>; }
interface GodrejMappings { products:Map<string,Array<{internal:string;unit:string}>>; }
function mapRows(w:XLSX.WorkBook,s:string,need:string[]){const sh=w.Sheets[s];if(!sh?.["!ref"])throw Error(`Sheet mapping ${s} tidak ditemukan atau kosong`);const r=XLSX.utils.sheet_to_json(sh,{header:1,raw:true,defval:null,blankrows:false}) as Row[], h=head(r,need,3);return {r,c:h.c,start:h.i+1};}
function unique(r:Row[],c:Map<string,number>,start:number,key:string,out:string,sheet:string){const m=new Map<string,string>();for(let i=start;i<r.length;i++){const a=tx(val(r[i],c,key)),b=tx(val(r[i],c,out));if(!a&&!b)continue;if(!b)continue;if(!a)throw Error(`${sheet} tidak lengkap pada baris ${i+1}`);if(m.has(a)&&m.get(a)!==b)throw Error(`${sheet} memiliki mapping konflik untuk ${a}`);m.set(a,b)}return m;}
export function parseKinoMappings(buf:Buffer|Uint8Array):KinoMappings {if(!buf?.byteLength)throw Error("File mapping kosong");const w=XLSX.read(buf,{type:"buffer",raw:true,cellFormula:false}),p=mapRows(w,"Mapping_Prd",["KODE ITEM","KODE ALIAS","SATUAN"]),products=new Map<string,{internal:string;unit:string}>();for(let i=p.start;i<p.r.length;i++){const a=tx(val(p.r[i],p.c,"KODE ALIAS")),b=tx(val(p.r[i],p.c,"KODE ITEM")),z=u(val(p.r[i],p.c,"SATUAN"));if(!a&&!b&&!z)continue;if(!a||!b||!z)throw Error(`Mapping_Prd tidak lengkap pada baris ${i+1}`);const old=products.get(a);if(old&&(old.internal!==b||old.unit!==z))throw Error(`Mapping_Prd memiliki mapping konflik untuk ${a}`);products.set(a,{internal:b,unit:z})}const cu=mapRows(w,"Mapping_Customer",["CODE KINO","CODE INTERNAL"]),sa=mapRows(w,"Mapping_Sls",["SLSMAN_ID","CODE INTERNAL"]);return {products,customers:unique(cu.r,cu.c,cu.start,"CODE KINO","CODE INTERNAL","Mapping_Customer"),salesmen:unique(sa.r,sa.c,sa.start,"SLSMAN_ID","CODE INTERNAL","Mapping_Sls")};}
export function parseGodrejMappings(buf:Buffer|Uint8Array):GodrejMappings {if(!buf?.byteLength)throw Error("File mapping kosong");const w=XLSX.read(buf,{type:"buffer",raw:true,cellFormula:false}),p=mapRows(w,"Pvt Map 1",["KODE PCPL","KODE BARANG WIN2","SATUAN FIX WIN"]),products=new Map<string,Array<{internal:string;unit:string}>>();for(let i=p.start;i<p.r.length;i++){const a=tx(val(p.r[i],p.c,"KODE PCPL")),b=tx(val(p.r[i],p.c,"KODE BARANG WIN2")),z=u(val(p.r[i],p.c,"SATUAN FIX WIN"));if([a,b,z].every(v=>!v||v==="(BLANK)"||v==="0"))continue;if(!a||!b||!z)throw Error(`Pvt Map 1 tidak lengkap pada baris ${i+1}`);const list=products.get(a)??[];if(!list.some(x=>x.internal===b&&x.unit===z))list.push({internal:b,unit:z});products.set(a,list)}return {products};}

export function parseAccurateSales(buf:Buffer|Uint8Array):CanonicalSalesLine[] {const r=rows(buf,"Rincian Faktur Penjualan"),h=head(r,["NO_NOTA","TANGGAL","KODE PELANGGAN INDUK","KODE_SALESMAN","KODE_BARANG","QTY_SATUANKECIL","SATUAN_KECIL","NILAI JUAL","POTONGAN","DPP","NILAI_PAJAK","JUMLAH","REM","JENIS_TRANSAKSI"]);return r.slice(h.i+1).map((x,o)=>{const line=h.i+o+2,q=num(val(x,h.c,"QTY_SATUANKECIL"),"QTY_SATUANKECIL",line);if(q<0)throw Error(`QTY_SATUANKECIL negatif pada baris ${line}`);const cust=req(x,h.c,"KODE PELANGGAN INDUK",line),sales=req(x,h.c,"KODE_SALESMAN",line),prod=req(x,h.c,"KODE_BARANG",line);return {source:"ACCURATE",sourceRowNumber:line,documentNumber:req(x,h.c,"NO_NOTA",line),orderNumber:ord(val(x,h.c,"REM"),"REM",line),transactionDate:date(val(x,h.c,"TANGGAL"),"TANGGAL",line),customerCodeRaw:cust,customerCodeInternal:cust,salesmanCodeRaw:sales,salesmanCodeInternal:sales,productCodeRaw:prod,productCodeInternal:prod,transactionClass:klass(val(x,h.c,"JENIS_TRANSAKSI")),quantitySmallest:q,unitSmallest:u(req(x,h.c,"SATUAN_KECIL",line)),grossAmount:mon(val(x,h.c,"NILAI JUAL"),"NILAI JUAL",line),discountAmount:mon(val(x,h.c,"POTONGAN"),"POTONGAN",line),dppAmount:mon(val(x,h.c,"DPP",line),"DPP",line),taxAmount:mon(val(x,h.c,"NILAI_PAJAK"),"NILAI_PAJAK",line),netAmount:mon(val(x,h.c,"JUMLAH"),"JUMLAH",line),mappingStatus:"OK"};});}
export function parseKinoSales(buf:Buffer|Uint8Array,m:KinoMappings):CanonicalSalesLine[] {const r=rows(buf,"Sheet1"),h=head(r,["CUSTCODE1","ORDER_NO","INVOICE_NO","INVOICE_DATE","PRODUCT_CODE","SALESMAN_ID","FLAG_BONUS","INVOICE_QTY","INVOICE_GROSS","INVOICE_TOTALLINEDISC","INVOICE_PROMO","INVOICE_CASHDISC","INVOICE_TAX","INVOICE_NET","PRD_UOM1"]),out:CanonicalSalesLine[]=[];for(let i=h.i+1;i<r.length;i++){const x=r[i],line=i+1,first=tx(x.find(y=>tx(y)));if(!first||first.startsWith("TOTAL FOR")||first==="GRAND TOTAL")continue;const raw=req(x,h.c,"PRODUCT_CODE",line),p=m.products.get(raw),sourceUnit=u(req(x,h.c,"PRD_UOM1",line)),flag=req(x,h.c,"FLAG_BONUS",line);if(flag!=="Y"&&flag!=="N")throw Error(`FLAG_BONUS harus Y/N pada baris ${line}`);const q=num(val(x,h.c,"INVOICE_QTY"),"INVOICE_QTY",line);if(q<0)throw Error(`INVOICE_QTY negatif pada baris ${line}`);const gross=mon(val(x,h.c,"INVOICE_GROSS"),"INVOICE_GROSS",line),disc=mon(val(x,h.c,"INVOICE_TOTALLINEDISC"),"INVOICE_TOTALLINEDISC",line)+mon(val(x,h.c,"INVOICE_PROMO"),"INVOICE_PROMO",line)+mon(val(x,h.c,"INVOICE_CASHDISC"),"INVOICE_CASHDISC",line),tax=mon(val(x,h.c,"INVOICE_TAX"),"INVOICE_TAX",line),net=mon(val(x,h.c,"INVOICE_NET"),"INVOICE_NET",line),status:MappingStatus=!p?"UNMAPPED_SKU":sourceUnit!==p.unit?"UNIT_CONVERSION_ERROR":"OK",cust=req(x,h.c,"CUSTCODE1",line),sales=req(x,h.c,"SALESMAN_ID",line);out.push({source:"PRINCIPAL",sourceRowNumber:line,documentNumber:req(x,h.c,"INVOICE_NO",line),orderNumber:ord(val(x,h.c,"ORDER_NO"),"ORDER_NO",line),transactionDate:date(val(x,h.c,"INVOICE_DATE"),"INVOICE_DATE",line),customerCodeRaw:cust,customerCodeInternal:m.customers.get(cust)??"",salesmanCodeRaw:sales,salesmanCodeInternal:m.salesmen.get(sales)??"",productCodeRaw:raw,productCodeInternal:p?.internal??`UNMAPPED:${raw}`,transactionClass:flag==="Y"?"BONUS":"NORMAL",quantitySmallest:q,unitSmallest:p?.unit??sourceUnit,grossAmount:gross,discountAmount:disc,dppAmount:gross-disc,taxAmount:tax,netAmount:net,mappingStatus:status});}return out;}
export function parseGodrejSales(buf:Buffer|Uint8Array,m:GodrejMappings,accurate:CanonicalSalesLine[]):CanonicalSalesLine[] {const r=rows(buf,"Sheet1"),h=head(r,["IV_NO","IV_DATE","CS_NO","PS_NO","INV_NO","IV_TOTPCS","IV_PRICE","IV_DISC1","IV_FRA"]),byOrder=new Map<string,Set<string>>(),out:CanonicalSalesLine[]=[];for(const a of accurate){const s=byOrder.get(a.orderNumber)??new Set<string>();s.add(a.productCodeInternal);byOrder.set(a.orderNumber,s)}const unsupported=["IV_DISC","IV_PPN","IV_STAMP","IV_DISREG","IV_DISADD","IV_DISCASH","IV_TOTDISC","IV_DISC2","IV_DISVALUE"];for(let i=h.i+1;i<r.length;i++){const x=r[i],line=i+1;if(!tx(x.find(y=>tx(y))))continue;for(const c of unsupported)if(h.c.has(c)&&num(val(x,h.c,c),c,line)!==0)throw Error(`${c} belum memiliki aturan pada baris ${line}`);const raw=req(x,h.c,"INV_NO",line),order=ord(val(x,h.c,"IV_NO"),"IV_NO",line),all=m.products.get(raw)??[],matches=all.filter(p=>byOrder.get(order)?.has(p.internal)),p=all.length===1?all[0]:matches.length===1?matches[0]:undefined,status:MappingStatus=!all.length?"UNMAPPED_SKU":!p?"INVALID_DATA":"OK",q=num(val(x,h.c,"IV_TOTPCS"),"IV_TOTPCS",line),price=num(val(x,h.c,"IV_PRICE"),"IV_PRICE",line),fra=num(val(x,h.c,"IV_FRA"),"IV_FRA",line),pct=num(val(x,h.c,"IV_DISC1"),"IV_DISC1",line);if(q<0||price<0||fra<=0)throw Error(`Nilai GDI tidak valid pada baris ${line}`);const grossValue=q*price/fra,discValue=grossValue*pct/100,gross=mon(grossValue,"GROSS",line),disc=mon(discValue,"DISKON",line),dpp=gross-disc,tax=mon((grossValue-discValue)*.11,"PAJAK",line),cust=req(x,h.c,"CS_NO",line),sales=req(x,h.c,"PS_NO",line);out.push({source:"PRINCIPAL",sourceRowNumber:line,documentNumber:req(x,h.c,"IV_NO",line),orderNumber:order,transactionDate:date(val(x,h.c,"IV_DATE"),"IV_DATE",line),customerCodeRaw:cust,customerCodeInternal:cust,salesmanCodeRaw:sales,salesmanCodeInternal:sales,productCodeRaw:raw,productCodeInternal:p?.internal??`INVALID:${raw}`,transactionClass:"NORMAL",quantitySmallest:q,unitSmallest:p?.unit??"",grossAmount:gross,discountAmount:disc,dppAmount:dpp,taxAmount:tax,netAmount:dpp+tax,mappingStatus:status});}return out;}

interface Agg {order:string;product:string;klass:TransactionClass;q:number;gross:number;disc:number;dpp:number;tax:number;net:number;status:MappingStatus;warnings:Set<string>;rows:number[];}
function aggregate(lines:CanonicalSalesLine[]){const m=new Map<string,Agg>();for(const x of lines){const key=`${x.orderNumber}|${x.productCodeInternal}|${x.transactionClass}`,a=m.get(key)??{order:x.orderNumber,product:x.productCodeInternal,klass:x.transactionClass,q:0,gross:0,disc:0,dpp:0,tax:0,net:0,status:"OK" as MappingStatus,warnings:new Set<string>(),rows:[]};a.q+=x.quantitySmallest;a.gross+=x.grossAmount;a.disc+=x.discountAmount;a.dpp+=x.dppAmount;a.tax+=x.taxAmount;a.net+=x.netAmount;a.rows.push(x.sourceRowNumber);if(x.mappingStatus!=="OK")a.status=x.mappingStatus;if(x.source==="PRINCIPAL"&&!x.customerCodeInternal)a.warnings.add("UNMAPPED_CUSTOMER");if(x.source==="PRINCIPAL"&&!x.salesmanCodeInternal)a.warnings.add("UNMAPPED_SALESMAN");m.set(key,a)}return m;}
function reconcile(accurate:CanonicalSalesLine[],principal:CanonicalSalesLine[],opt:{valueTolerance?:number}):ReconciliationOutput {const tol=Math.round((opt.valueTolerance??1)*SCALE);if(!Number.isSafeInteger(tol)||tol<0)throw Error("valueTolerance tidak valid");const a=aggregate(accurate),p=aggregate(principal),results:ReconciliationResult[]=[];for(const key of new Set([...a.keys(),...p.keys()])){const l=a.get(key),r=p.get(key),qd=(l?.q??0)-(r?.q??0),pairs: Array<[AmountComponent,number,number]>=l&&r?[["gross",l.gross,r.gross],["discount",l.disc,r.disc],["dpp",l.dpp,r.dpp],["tax",l.tax,r.tax],["net",l.net,r.net]]:[],diff=pairs.filter(([,x,y])=>Math.abs(x-y)>tol).map(([component,x,y])=>({component,accurate:x/SCALE,kino:y/SCALE,difference:(x-y)/SCALE})),vm=diff.length>0;let status:ReconciliationStatus;if(r?.status==="INVALID_DATA")status="INVALID_DATA";else if(r?.status==="UNMAPPED_SKU")status="UNMAPPED_SKU";else if(r?.status==="UNIT_CONVERSION_ERROR")status="UNIT_CONVERSION_ERROR";else if(!l)status="MISSING_INTERNAL";else if(!r)status="MISSING_PRINCIPAL";else if(qd&&vm)status="QTY_AND_VALUE_MISMATCH";else if(qd)status="QTY_MISMATCH";else if(vm)status="VALUE_MISMATCH";else status="MATCH";const x=l??r!;results.push({orderNumber:x.order,internalProductCode:x.product,transactionClass:x.klass,accurateQuantity:l?.q??0,principalQuantity:r?.q??0,quantityDifference:qd,accurateNet:(l?.net??0)/SCALE,principalNet:(r?.net??0)/SCALE,valueDifference:((l?.net??0)-(r?.net??0))/SCALE,amountDifferences:diff,status,warnings:[...new Set([...(l?.warnings??[]),...(r?.warnings??[])])],accurateSourceRows:l?.rows??[],principalSourceRows:r?.rows??[]});}const summary=Object.fromEntries(STATUSES.map(s=>[s,0])) as Record<ReconciliationStatus,number>;for(const x of results)summary[x.status]++;return {accurateLines:accurate,kinoLines:principal,results,summary};}
export function reconcileKinoSales(a:Buffer|Uint8Array,k:Buffer|Uint8Array,m:Buffer|Uint8Array,o:{valueTolerance?:number}={}) {return reconcile(parseAccurateSales(a),parseKinoSales(k,parseKinoMappings(m)),o);}
export function reconcileGodrejSales(a:Buffer|Uint8Array,g:Buffer|Uint8Array,m:Buffer|Uint8Array,o:{valueTolerance?:number}={}) {const accurate=parseAccurateSales(a);return reconcile(accurate,parseGodrejSales(g,parseGodrejMappings(m),accurate),o);}
